### ISSUE TITLE
Need Fix File (mixins)

### ISSUE THREAD

**Issue by Vitokhv** [nvb-uy/Necronomicon#5]
File: necronomicon.forge.mixins.json
This file does not contain line `"minVersion": "0.8",` and the server complains in red that it is missing
Version of the mod used: Necronomicon-Forge-1.4.2.jar
Version of the server used: forge-1.20.1-47.3.0-installer.jar

I had to replace the file in the mod with the corrected one so that the error did not appear
I hope you fix the bug for version 1.20.1

> {
>   "required": false,
>   "minVersion": "0.8",
>   "package": "elocindev.necronomicon.mixin.forge",
>   "compatibilityLevel": "JAVA_17",
>   "injectors": {
>     "defaultRequire": 1
>   },
>   "mixins": [
>     "AnimatedItemNameMixin"
>   ],
>   "client": [],
>   "server": [],
>   "refmap": "Necronomicon-1.19.4-forge-refmap.json"
> }

**Comment by nvb-uy** [comment]
This error is just a warning, it does not cause any issues besides the log being written. There is no need for you to edit the file and if you're crashing, read the rest of the log because this is NOT the issue.
