### ISSUE TITLE
Something has been bothering me about this mod for the past 2 years and I need to ask the dev about it

### ISSUE THREAD

**Issue by theLucidLibrarian** [nvb-uy/Necronomicon#6]
Ok, so. My username on other platforms is theLucidLibrary/theLucidLibrarian, and I needed a profile picture to go with it. So I just searched up "theLucidLibrary" in google, and found this png: 
![637820970154849717-3169969706](https://github.com/user-attachments/assets/60afaaf2-df18-4d26-b0da-38fc6318033c)

It says it comes from a Curseforge mod, but every time I try to download it, it just redirects me to a 404 error page.
https://www.curseforge.com/minecraft/mc-mods/lucid-library/download/3788881

PLEASE, do you know ANYTHING about this mod? Because it's been driving me INSANE.

- Lucid

**Comment by nvb-uy** [comment]
Lucid Library was the previous name of Necronomicon. And yes I made that picture you're using :p
