### ISSUE TITLE
Error during startup -1.20.1 - "minVersion" missing

### ISSUE THREAD

**Issue by velox-resurrected** [nvb-uy/Necronomicon#7]
When launching the game, under lastest.log file you can see a mixin error.

"Mixin config necronomicon.forge.mixins.json does not specify "minVersion" property"

**Comment by nvb-uy** [comment]
This is NOT a critical error and will not affect your game. If you're crashing, it's not because of this, please read the full log to see whatever is causing your crash.

**Comment by velox-resurrected** [comment]
Understandable, but was reporting it not as a critical issue, and not crashing either, was just reporting due to it spamming the logs when starting the game, and it being an error message(not normal function). Marking down as Dev - known issue.
